config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post '/users/search', to: 'users#search', as: 'search_user'

  resources :users, only: :show
  resources :checkins, only: %i[new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  belongs_to :pulse_status

  validates :location, length: { maximum: 140 }
  validates :message, length: { maximum: 140 }
end

app/models/pulse_status.rb
class PulseStatus < ApplicationRecord
  def display_name
    name.capitalize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         # rm until email set up:
         #  :recoverable,
         :rememberable, :validatable

  validates :name, presence: true,
                   length: { minimum: 1 },
                   uniqueness: true
  has_many :checkins, dependent: :destroy

  def latest_checkins(count = 5)
    checkins.order(created_at: :desc).limit(count)
  end

  def check_in!(pulse_status, location = '', message = '')
    Checkin.create!(user: self,
                    pulse_status: pulse_status,
                    location: location,
                    message: message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  def new
    @checkin = Checkin.new
  end

  def create
    @checkin = Checkin.new(checkin_params)
    @checkin.user = current_user

    pulse_status = PulseStatus.find(params[:checkin][:pulse_status_id])
    @checkin.pulse_status = pulse_status

    if @checkin.save
      redirect_to user_path(current_user.name)
    else
      render :new
    end
  end

  def show
  end

  private

  def checkin_params
    params.require(:checkin)
          .permit(:location, :message, :pulse_status_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show search]
  before_action :find_user, only: %i[search show]

  def show
    if params[:id].to_i == @user.id
      redirect_to user_path(@user.name)
    end
  end

  def search
    redirect_to user_path(@user.name)
  end

  private

  def find_user
    begin
      @user = User.find_by(name: params[:id]) ||
              User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "User \"#{params[:id]}\" not found."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pulse_helper.rb
module PulseHelper
  def checkin_bs_context_name(checkin)
    contexts = {
      'safe' => 'success',
      'in danger' => 'warning',
      'injured' => 'danger',
      'need help' => 'danger'
    }
    contexts[checkin.pulse_status.name] || 'info'
  end
end

app/views/checkins/new.html.erb
<div class="container">
  <h1 class="text-center">Check In</h1>
  <p class="text-center mb-0">How are you doing right now?</p>
  <p class="text-center">After you check in, people who visit your profile page will see your update there.</p>

  <%= simple_form_for(@checkin, html: { autocomplete: :off }) do |f| %>
    <%= f.association :pulse_status,
                      label: 'Status',
                      include_blank: false,
                      label_method: :display_name,
                      class: "status-name" %>
    <%= f.input :location,
                label: 'Location (optional)',
                placeholder: 'Where are you?' %>
    <%= f.input :message,
                label: 'Message (optional)',
                placeholder: 'Share a little more info' %>

    <%= f.button :submit, 'Check In', class: 'btn btn-primary w-100' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pulse - safety status updater</title>
    <meta name="description" content="Let the people who care about you know when you're safe &emdash; and when you're not.">

    <meta property='og:title' content="Pulse" data-dynamic='true' />
    <meta property='og:site_name' content='Pulse' data-dynamic='true' />
    <meta property='og:url' content='https://safetypulse.herokuapp.com' />
    <meta property='og:description' content="Pulse - safety status updater"  data-dynamic='true' />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container page-content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="header">
  <h1 class="mb-0 pb-0 text-center">Pulse</h1>
  <div class="intro mt-3">
    <p class="text-center">
      <strong>Pulse</strong> is a simple tool to help update people who are affected by disruptive events such as natural disasters, terror attacks, and wars.
    </p>

    <div class="my-5">
      <div class="mb-2">
        <% if user_signed_in? %>
          <%= link_to new_checkin_path, class: 'btn btn-primary w-100' do %>
            <i class="fas fa-heartbeat small"></i> Check in
          <% end %>
        <% else %>
          <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary w-100' %>
        <% end %>
      </div>
      <div>
        <%= render 'shared/find_user_form' %>
      </div>
    </div>

    <h4>How it Works</h4>
    <div class="row">
      <div class="col-1 text-right">
        <i class="fas fa-user-circle"></i>
      </div>
      <div class="col-11">
        <p>You can see anyone's profile page without creating an account or signing in.</p>
      </div>
      <div class="col-1 text-right">
        <i class="fas fa-heartbeat"></i>
      </div>
      <div class="col-11">
        <p>If you create an account, you can quickly <strong>check in</strong> whenever you need, to let people know how you are.</p>
      </div>
      <div class="col-1 text-right">
        <i class="fas fa-search"></i>
      </div>
      <div class="col-11">
        <p>Type someone's <strong>user name</strong> in the <strong>find bar</strong> to see their profile page.</p>
      </div>
      <div class="col-1 text-right">
        <i class="fas fa-quote-left"></i>
      </div>
      <div class="col-11">
        <p>Here is an <strong><%= link_to 'example', user_path('demo') %></strong> of a user's profile page.</p>
      </div>
    </div>



    <div class="my-5">
      <h4>Important</h4>
      <small>
        <ul>
          <li>Pulse provides this service as a helpful tool, and makes no guarantees for information accuracy or reliability. You use this service entirely under your own responsibility.</li>
          <li>Pulse <strong>will not act</strong> upon users' information, and is <strong>not a replacement for local emergency services.</strong></li>
        </ul>
      </small>
    </div>
  </div>
</div>
<div class="page-content text-center flex-grow-1 d-flex flex-column justify-content-center">

</div>

app/views/shared/_find_user_form.html.erb
<%= form_with url: search_user_path,
              class: 'form-inline nav-find-user',
              html: { autocomplete: 'off' } do |f| %>
  <%= f.text_field :id, class: 'form-control flex-grow-1 ', type: 'search', placeholder: 'Find User', :'aria-label' => 'Find User' %>
  <button class="btn btn-success my-2 my-sm-0 flex-shrink-0" type="submit">
    <span><i class="small fas fa-search"></i> Find</span>
  </button>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show w-100 m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show w-100 m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="text-center small">&copy; 2021 Yair Gordon</div>
  <div class="text-center small">Icons &copy; <a class="text-white" href="https://fontawesome.com/license">FontAwesome</div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'logo.png', alt: 'Pulse', height: 30 %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active my-2 my-md-0 mr-md-2">
          <%= link_to new_checkin_path, class: "nav-link btn btn-primary" do %>
            <i class="fas fa-heartbeat small"></i> Check in
          <% end %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= render 'shared/find_user_form' %>
      </li>

      <li class="nav-item mx-sm-2">
        <div class="form-inline">
          <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-secondary" %>
            <%= link_to user_path(current_user.name), class: 'btn btn-secondary ml-2 flex-grow-1' do %>
              <i class="small fas fa-user-circle text-white"></i> Profile
            <% end %>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="header text-center">
    <h2 class="mb-2 pb-0"><i class="small fas fa-user-circle text-muted"></i> <%= @user.name %></h2>
    <% if user_signed_in? && @user == current_user %>
      <p>
        <span class="text-muted">This is your page</span>.
        Share it.

    <% end %>
  </div>

  <h5>Latest Checkins</h5>
  <% if @user.latest_checkins.empty? %>
    <p class="text-center">No checkins yet.</p>
  <% else %>
    <ul class="list-group rounded-lg">
      <% @user.latest_checkins.each do |checkin| %>
        <li class="list-group-item list-group-item-<%= checkin_bs_context_name(checkin) %>">
          <div class="d-flex w-100 justify-content-between align-items-center">
            <span class="h4"><%= checkin.pulse_status.display_name %></span>
            <span class="badge badge-primary badge-pill pill-time-ago">
              <%= time_ago_in_words(checkin.created_at) %>
            </span>
          </div>
          <% if checkin.message.length.positive? %>
              <p class="mb-0">
                <sup><i class="fas fa-quote-left"></i></sup>
                <%= checkin.message %>
                <sup><i class="fas fa-quote-right"></i></sup>
              </p>
          <% end %>
          <% unless checkin.location.empty? %>
            <div>
              <i class="fas fa-map-marker-alt"></i>
              <%= checkin.location %>
            </div>
          <% end %>
          <small class="text-muted"><%= local_time(checkin.created_at) %></small>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>